name: python CI

on: [push, pull_request]

jobs:
  tox_test:
    name: Run tox (${{ matrix.python_version }})
    strategy:
      matrix:
        python_version:
        - 2.7
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    # - name: Analysing the code with pylint
    #   run: |
    #     pip install pylint
    #     pylint $(git ls-files '*.py')

    - name: Run unit tests using tox
      run: tox

  Build_and_publish:
    name: Run tox (${{ matrix.python_version }})
    strategy:
      matrix:
        python_version:
        - 3.6
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    # - name: Analysing the code with pylint
    #   run: |
    #     pip install pylint
    #     pylint $(git ls-files '*.py')

    - name: Send mail notifier about status of pipeline
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp-mail.outlook.com
        server_port: 587
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: OneViewSDK Daily Deployment Results â€“ ${{job.status}}
        body: |
          Hi All,
          OneViewSDK daily deployment on build 6.30.00 is considered a ${{job.status}} for Synergy Composer and VM appliances.
          link: ${{ EVENT_PAYLOAD.check_run.url }}
          
          Thanks,
          OneView SDK Deployment Automation
        to: bala-sai-harika.chebrolu@hpe.com
        from: github-actions
        priority: high

    - name: Run unit tests using tox
      run: tox

    - name: Check coverage
      uses: AndreMiras/coveralls-python-action@develop
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
        flag-name: 'Unit Test'
        debug: true