name: python CI

on:
- pull_request

jobs:
  tox_test:
    name: Run tox (${{ matrix.python_version }})
    strategy:
      matrix:
        python_version:
        - 3.8
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tox tests
      run: tox

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
       target_branch: gh-pages
       keep_history: true
       build_dir: docs/build/html/.
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
        flag-name: 'Unit Test'
        debug: true
